AllCops:
  TargetRubyVersion: 2.6.7
  NewCops: enable
  SuggestExtensions: false

StringLiterals:
  Enabled: false

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/FirstArgumentIndentation:
  Enabled: false

Layout/FirstArrayElementIndentation:
  Enabled: false

Layout/FirstHashElementLineBreak:
  Enabled: true

Layout/LineLength:
  Max: 130
  Exclude:
    - 'assets/js/view/svg_tokens/**/*'

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/MultilineHashKeyLineBreaks:
  Enabled: true

Layout/MultilineOperationIndentation:
  Enabled: false

Lint/MissingSuper: # TODO enable & check offenses
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: true
  AllowUnusedKeywordArguments: true

Lint/UselessMethodDefinition: # TODO enable & check offenses
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Naming/VariableNumber: # TODO enable & check offenses, default or snake_case?
  Enabled: false
  # EnforcedStyle: snake_case

Naming/MethodParameterName:
  Enabled: false

Style/ClassVars:
  Enabled: false

# all (6) duplicated loops are used on purpose and for good reason
Style/CombinableLoops:
  Enabled: false

Style/CommandLiteral:
  Enabled: true
  EnforcedStyle: mixed

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

# unsafe, problems with 1860
Style/HashEachMethods:
  Enabled: false

# code readibility: case trumps hash-lookup
Style/HashLikeCase:
  Enabled: false

Style/OptionalBooleanParameter: # TODO enable & check offenses
  Enabled: false

# conflicts with Style/MutableConstant
Style/RedundantFreeze:
  Enabled: false

# enabling would break compiling deps!
Style/SlicingWithRange:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/DoubleNegation:
  Enabled: false
